#Checks if every module, class and function has a description.

name: are descriptions documented?
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
      - name: Check for missing descriptions
        run: python docs/check_docstrings.py
